### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by alesdotio**
Adds python3 support and drops python2 support since requirements don't allow it.

TODO:
- [x] update circleci base image

### CODE REVIEW

**Comment by SuneKjaergaard** [comment]
Closed?

**Comment by alesdotio** [comment]
I'm trying to make it compatible with Python 2 as well but it seems it won't be possible because of pyzmq

**Comment by guy881** [comment]
@alesdotio did you try running 2to3 or sth. here as well?

**Comment by KristianOellegaard** [comment]
LGTM

**Pull request merged**
